# Generated by Django 3.1.2 on 2021-01-18 15:13

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Article',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('article_title', models.CharField(max_length=200, verbose_name='Название статьи')),
                ('article_text', models.TextField(verbose_name='Текст статьи')),
                ('article_date', models.DateTimeField(verbose_name='Дата публткации')),
                ('article_author', models.CharField(max_length=50, verbose_name='Имя автора')),
            ],
            options={
                'verbose_name': 'Статья',
                'verbose_name_plural': 'Статьи',
            },
        ),
        migrations.CreateModel(
            name='Comment',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('comment_author', models.CharField(max_length=50, verbose_name='Имя автора')),
                ('comment_text', models.CharField(max_length=200, verbose_name='Текст комментария')),
                ('comment_date', models.DateTimeField(verbose_name='Дата отправки комментария')),
                ('comment', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='articles.article', verbose_name='Статья')),
            ],
            options={
                'verbose_name': 'Комментарий',
                'verbose_name_plural': 'Комментарии',
            },
        ),
        migrations.CreateModel(
            name='Answer',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('answer_author', models.CharField(max_length=50, verbose_name='Имя автора')),
                ('answer_text', models.CharField(max_length=200, verbose_name='Текст комментария')),
                ('answer_date', models.DateTimeField(verbose_name='Дата отправки ответа')),
                ('answer', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='articles.comment', verbose_name='Комментарий')),
            ],
            options={
                'verbose_name': 'Ответ',
                'verbose_name_plural': 'Ответы',
            },
        ),
    ]
