# Generated by Django 3.1.2 on 2021-01-20 16:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('articles', '0002_article_url'),
    ]

    operations = [
        migrations.AddField(
            model_name='answer',
            name='answer_image',
            field=models.ImageField(null=True, upload_to='image/', verbose_name='Изображение автора ответа'),
        ),
        migrations.AddField(
            model_name='comment',
            name='comment_image',
            field=models.ImageField(null=True, upload_to='image/', verbose_name='Изображение автора коммента'),
        ),
        migrations.AlterField(
            model_name='article',
            name='article_date',
            field=models.DateTimeField(verbose_name='Дата публикации'),
        ),
        migrations.AlterField(
            model_name='article',
            name='url',
            field=models.SlugField(default='', max_length=160, unique=True),
        ),
    ]
