# Generated by Django 3.1.2 on 2021-02-03 00:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('articles', '0003_auto_20210120_1912'),
    ]

    operations = [
        migrations.AlterField(
            model_name='answer',
            name='answer_image',
            field=models.ImageField(null=True, upload_to='answer_image/', verbose_name='Изображение автора ответа'),
        ),
        migrations.AlterField(
            model_name='comment',
            name='comment_date',
            field=models.DateTimeField(null=True, verbose_name='Дата отправки комментария'),
        ),
        migrations.AlterField(
            model_name='comment',
            name='comment_image',
            field=models.ImageField(null=True, upload_to='comment_image/', verbose_name='Изображение автора коммента'),
        ),
    ]
