# Generated by Django 3.1.2 on 2021-02-03 03:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('articles', '0005_auto_20210203_0320'),
    ]

    operations = [
        migrations.AddField(
            model_name='answer',
            name='answer_date',
            field=models.DateTimeField(null=True, verbose_name='Дата отправки ответа'),
        ),
        migrations.AddField(
            model_name='answer',
            name='answer_image',
            field=models.ImageField(null=True, upload_to='answer_image/', verbose_name='Изображение автора ответа'),
        ),
        migrations.AddField(
            model_name='comment',
            name='comment_date',
            field=models.DateTimeField(null=True, verbose_name='Дата отправки комментария'),
        ),
        migrations.AddField(
            model_name='comment',
            name='comment_image',
            field=models.ImageField(null=True, upload_to='comment_image/', verbose_name='Изображение автора коммента'),
        ),
    ]
