# Generated by Django 3.1.2 on 2021-02-03 14:49

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('articles', '0006_auto_20210203_0611'),
    ]

    operations = [
        migrations.AddField(
            model_name='comment',
            name='parent',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to='articles.comment', verbose_name='Родитель'),
        ),
        migrations.DeleteModel(
            name='Answer',
        ),
    ]
