# Generated by Django 3.1.2 on 2021-03-15 19:34

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('articles', '0009_auto_20210315_2212'),
    ]

    operations = [
        migrations.AlterField(
            model_name='comment',
            name='comment_date',
            field=models.DateTimeField(default=datetime.time(0, 0), null=True, verbose_name='Дата отправки комментария'),
        ),
    ]
