# Generated by Django 3.1.2 on 2021-03-15 19:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('articles', '0010_auto_20210315_2234'),
    ]

    operations = [
        migrations.AlterField(
            model_name='comment',
            name='comment_date',
            field=models.DateTimeField(null=True, verbose_name='Дата отправки комментария'),
        ),
    ]
